TestFlask/models.py
from app import db
from datetime import datetime
import re
import uuid
from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', str(s))


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = slugify(str(uuid.uuid4()))

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.name:
            self.slug = slugify(self.name)
        else:
            self.slug = slugify(str(uuid.uuid4()))

    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)


# Flask Security #

roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer(), db.ForeignKey('role.id')),
                       )


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(225))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

TestFlask/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField("Title")
    body = TextAreaField("Body")

TestFlask/app.py
from flask import Flask, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore, Security, current_user

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# ADMIN #
from models import *


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)


class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']


class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']


admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

# Flask Security #
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

TestFlask/main.py
from app import app
from posts.blueprint import posts
import view

app.register_blueprint(posts, url_prefix='/posts')

if __name__ == '__main__':
    app.run()

TestFlask/posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Post, Tag
from sqlalchemy import func
from .forms import PostForm
from app import db

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something wrong')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', form=form, post=post)


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        all_posts = Post.query.filter(func.lower(Post.title).contains(func.lower(q)) |
                                      func.lower(Post.body).contains(func.lower(q))).all()
    else:
        all_posts = Post.query.order_by(Post.id.desc())

    pages = all_posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', posts=all_posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    tag_posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, tag_posts=tag_posts)

TestFlask/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New Post
{% endblock %}

{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">

            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-laber') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-dark">Create</button>
        </form>
    </div>
{% endblock %}

TestFlask/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit Post
{% endblock %}

{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">

            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-laber') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-dark">Edit</button>
        </form>
    </div>
{% endblock %}

TestFlask/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}

    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </p>
    {% endfor %}

    <nav>
      <ul class="pagination">

        <li {% if not pages.has_prev %} class="page-item disabled" {% else %} class="page-item" {% endif %}>
          <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>

        {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %} class="page-item active" {% else %} class="page-item" {% endif %}>
                <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
        {% endfor %}

        <li {% if not pages.has_next %} class="page-item disabled" {% else %} class="page-item" {% endif %}>
          <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>

      </ul>
    </nav>

{% endblock %}

TestFlask/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="badge badge-success">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
    <div class="main-content">
        {{ post.body }}
    </div>
{% endblock %}

TestFlask/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
        {% for post in tag_posts %}
            <div class="posts">
                <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
            </div>
{#            <div class="main-content">#}
{#                {{ post.body }}#}
{#            </div>#}
        {% endfor %}
{% endblock %}

TestFlask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %} | Flask app
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href=" {{ url_for('index') }} ">Flask</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href=" {{ url_for('posts.index') }} ">Blog <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href=" {{ url_for('posts.create_post') }} ">Create <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
              {% if current_user.has_role('admin') %}
                <a class="nav-link" href="/admin">Admin <span class="sr-only">(current)</span></a>
              {% endif %}
          </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" name="q" value="{{ request.args.get('q', '') }}" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

      </div>
    </nav>

    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}
                {% endblock %}
            </h1>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

TestFlask/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    Main Page
{% endblock %}

{% block content %}
    <div class="col-md-8">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aut cumque exercitationem expedita,
        incidunt inventore iusto labore, modi, nemo quaerat quam repellat sed ullam voluptate voluptatibus.
        Aliquid culpa error modi? Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Consequuntur dolore excepturi facilis iure iusto magni odio quo sapiente, sequi sint.</p>
        <p>Culpa deserunt dicta impedit ipsam labore porro quaerat reprehenderit velit. Lorem ipsum dolor sit amet,
        consectetur adipisicing elit. Amet autem culpa delectus deserunt doloremque, exercitationem hic inventore
        iusto molestias nisi nostrum odio quaerat quas quis rem temporibus unde velit veniam.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aut cumque exercitationem expedita,
        incidunt inventore iusto labore, modi, nemo quaerat quam repellat sed ullam voluptate voluptatibus.</p>
        <p>Aliquid culpa error modi? Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Consequuntur dolore excepturi facilis iure iusto magni odio quo sapiente, sequi sint.
        Culpa deserunt dicta impedit ipsam labore porro quaerat reprehenderit velit. Lorem ipsum dolor sit amet,
        consectetur adipisicing elit. Amet autem culpa delectus deserunt doloremque, exercitationem hic inventore
        iusto molestias nisi nostrum odio quaerat quas quis rem temporibus unde velit veniam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aut cumque exercitationem expedita,
        incidunt inventore iusto labore, modi, nemo quaerat quam repellat sed ullam voluptate voluptatibus.
        Aliquid culpa error modi? Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Consequuntur dolore excepturi facilis iure iusto magni odio quo sapiente, sequi sint.
        Culpa deserunt dicta impedit ipsam labore porro quaerat reprehenderit velit. Lorem ipsum dolor sit amet,
        consectetur adipisicing elit. Amet autem culpa delectus deserunt doloremque, exercitationem hic inventore
        iusto molestias nisi nostrum odio quaerat quas quis rem temporibus unde velit veniam.</p>
    </div>
{% endblock %}

TestFlask/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

TestFlask/templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content_title %}
        {{ _('Login') }}
{% endblock %}

{% block content %}

    <div class="col-md-6 col-md-offset-3">
        {% from "security/_macros.html" import render_field_with_errors, render_field %}
        {% include "security/_messages.html" %}
        <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
          {{ login_user_form.hidden_tag() }}
          {{ render_field_with_errors(login_user_form.email, class='form-control') }}
          {{ render_field_with_errors(login_user_form.password, class='form-control') }}
          {{ render_field_with_errors(login_user_form.remember) }}
          {{ render_field(login_user_form.next) }}
          {{ render_field(login_user_form.submit, class='btn btn-dark') }}
        </form>
        {% include "security/_menu.html" %}
    </div>

{% endblock %}